name: train_booking
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  screenshot: ^3.0.0
  gal: ^2.0.1
  intl: ^0.20.0
  path_provider: ^2.1.0
  image_picker: ^1.2.1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/Rubik.ttf
